### PR TITLE
improved docstrings in circ_deque.jl

### PR DESCRIPTION
**Pull request by AtsushiSakai**
I realized the circ_deque.jl is missing some docstrings like #549. So I improved it.

### CODE REVIEW

**Comment by oxinabox** [comment]
A bunch of these don't need docstrings at all as the docstring in `Base` is fine for them.

```
help?> length
search: length

  length(collection) -> Integer

  Return the number of elements in the collection.
```

**Comment by AtsushiSakai** [comment]
@oxinabox Thank you for your reviewing. Then I removed unnecessary docstrings.

**Comment by oxinabox** [comment]
LGTM, thanks

**Comment by AtsushiSakai** [comment]
@oxinabox By the way. I found other many files are missing docstrings. Would you like me to keep fixing these files? If not, I will stop to make a PR.

**Comment by oxinabox** [comment]
Yeah sure, keep going its great.
I really appreciate it.

**Pull request merged**
