### PR TITLE
Doc: "unrolled linked list" change [ci skip]

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I could add "readme" to this (the similar one already pending). Or just wait for it?

**Comment by PallHaraldsson** [comment]
Hmm, I remember [ci skip] working before, if I start with it..

**Comment by oxinabox** [comment]
just keep them separate.
Weird that travis seems to still be trying to run even with the [ci skip]

**Comment by oxinabox** [comment]
thanks

**Comment by kmsquire** [comment]
As I mentioned in the other issue, while the underlying implementation for `Dequeue`s is similar to an unrolled linked list, I don't think this PR is actually accurate.  (Sorry, I thought I mentioned that here as well...)

**Comment by oxinabox** [comment]
Yeah I saw that . It was my thought that while not perfectly accurate, it was more accurate than not, and so better than not having this .
Sorry if I over stepped.
I can either fix the docs to be "implemented similar to a unrolled linked list",
or make a PR or issue to fix it so it **is** an unrolled linked list.

**Comment by kmsquire** [comment]
👍 Either way works for me.  Whatever you have time for.

**Pull request merged**
