### PR TITLE
Update the version of Documenter.jl

### LINKED ISSUE #839: The `dev` documentation is not up to date.
https://juliacollections.github.io/DataStructures.jl/dev/ is not updated after enabling GitHub actions (https://github.com/JuliaCollections/DataStructures.jl/pull/714).
This issue is the same as https://github.com/JuliaArrays/StaticArrays.jl/issues/870, and can be solved by updating the version of Documenter.jl.

### PR DESCRIPTION
**Pull request by hyrodium**
This PR fixes #839.

### CODE REVIEW

**Comment by oxinabox** [comment]
Are you able to go through and fix the broken doctests?

**Comment by hyrodium** [comment]
>Are you able to go through and fix the broken doctests?

Finished!

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
Thanks!

**Comment by StephenVavasis** [comment]
This PR also closes my issue 819.  I am currently locked out of Github because I didn’t turn on 2FA before their deadline.  I have opened a ticket with the Github helpdesk to see if I can regain access. But if someone else wants to close 819, that would be fine.

**Comment by hyrodium** [comment]
x-ref: https://github.com/JuliaCollections/DataStructures.jl/issues/819

**Pull request merged**
