### PR TITLE
Improve DefaultDict doc

### LINKED ISSUE #364: Deprecated doc for construction of DefaultDict
Hello,

I noticed in doc the following construction of DefaultDict 

https://github.com/JuliaCollections/DataStructures.jl/blame/c31f17f0d0dead44ae7766b36fd880dcae666a9d/doc/src/default_dict.md#L18

but this kind of construction is deprecated so it shouldn't be in doc

```julia
julia> DefaultDict(String, Int, 0)
WARNING: DefaultDict(::Type{K}, ::Type{V}, default) where {K, V} is deprecated, use DefaultDict{K, V}(default) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] DataStructures.DefaultDict(::Type{String}, ::Type{Int64}, ::Int64) at .\deprecated.jl:57
 [3] eval(::Module, ::Any) at .\boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:66
 [5] macro expansion at .\REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
DataStructures.DefaultDict{String,Int64,Int64} with 0 entries

julia> DefaultDict{String, Int}(0)
DataStructures.DefaultDict{String,Int64,Int64} with 0 entries
```

This issue is comparable to #340

Kind regards

### PR DESCRIPTION
**Pull request by scls19fr**
with setup/repl macro

Closes #364
Helps #360 
Replaces #365

### CODE REVIEW

**Comment by scls19fr** [comment]
This PR shouldn't be merged for now because Documenter.jl repl/setup macros seems to be buggy when using CRLF EOL.

After saving this `default_dict.md` file with LF as EOL, local build of doc is correctly rendered but using such EOL is not a correct workaround as all other files are using CRLF and git complains when adding it

    warning: LF will be replaced by CRLF in docs/src/default_dict.md.
    The file will have its original line endings in your working directory.

See https://github.com/JuliaDocs/Documenter.jl/issues/790 and https://github.com/JuliaDocs/Documenter.jl/issues/749

Waiting for @mortenpi / @fredrikekre (or others [Documenter.jl contributors](https://github.com/JuliaDocs/Documenter.jl/graphs/contributors)) to fix it

**Comment by kmsquire** [comment]
Can you add a commit before this one, which changes all doc files to use LF instead of CRLF?

**Comment by scls19fr** [comment]
Sorry @kmsquire but I don't understand why I should do that.

Under Windows, git is replacing automatically LF with CRLF
See https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

Do you know a command line to do it quickly?

**Comment by fredrikekre** [comment]
Documenter v19.5 is released with the bugfix included so if that was the problem here you are good to go.

**Pull request merged**
