### PR TITLE
Mark as 0.18-DEV and remove deprecations

### LINKED ISSUE #496: Deprecate then Remove ClassifierCollections
`ClassifierCollection`s is just a really weird data structure,
that I do not think is at all standard;
and I would be surprised if any julia code compatible with the current version of DataStructures was using it.

Please correct me if I am wrong.

It was added in
 https://github.com/JuliaCollections/DataStructures.jl/commit/064e5732df60d83256c1c852cf9f84dc13e5c39d
and basically had not changed since.
It has been in this package since before we had things like PRs being used by maintainers.
Wildwest days.

Somethings were added because they seemed useful for various projects and needed to go *Somewhere*.
(Similar for some of the weirder stuff in other old packages like StatsBase)
But now this is a package with over 750 dependents,
so we should try and keep to something vaguely standard.

### LINKED ISSUE #577: Prepare for release 0.18
#578 requires release of a breaking version.

List of other things we want to do before releasing 0.18:
 - [x] Delete deprecated `ClassifierCollection` 
 - [x] Delete all things in `deprecations`
 - [ ] deprecate `find_root` (see #603 )

### PR DESCRIPTION
**Pull request by oxinabox**
closes #577 

closes #496 

Follows up on https://github.com/JuliaCollections/DataStructures.jl/pull/603#issuecomment-612401679
and deprecates `find_root`

Required to be merged before #547

### CODE REVIEW

**Comment by davidanthoff** [comment]
PLEASE, make it 1.0.0! So that going forward you have the option to do minor, patch and major releases.

**Comment by oxinabox** [comment]
@davidanthoff  see https://github.com/JuliaCollections/DataStructures.jl/issues/479

Can't do it this release as it still has deprecations added.
Further there are pending breaking issues still open,
and we haven't completed the audit of the code base to be sure we don't have any Julia 0.3 style constructors, or other issues from not following the Julia 1.0 APIs. (like `push!` returning the value rather than the collection etc).
I am keen to get to 1.0 also, but not if I know that i will be tagging 2.0 soon after.

**Comment by davidanthoff** [comment]
I think there is zero harm in a 2.0 shortly after a 1.0, who cares? But going 1.0 now allows you to do minor and patch releases in the meantime, which is a great benefit to downstream packages because it becomes clear what is what. I think this fixation on 1.0 as a somewhat special version really is not a good match with the fact that semver plays an important role in the package resolution story in Julia.

**Comment by oxinabox** [comment]
While I do agree, in general and personally, I just am not willing to commit to that position on DataStructures.jl.
Because it is such a public package, and that is not the standard the community follows. Not yet at least.
Make the case on any other package I maintained and I would be seriously considering it, but not DataStructures.

(When we started talking about general registry, I argued that it should not accept packages before they tagged 1.0)

**Pull request merged**
