### PR TITLE
Fix loading on 0.7

### PR DESCRIPTION
**Pull request by yuyichao**
Replaces https://github.com/JuliaCollections/DataStructures.jl/pull/328

### CODE REVIEW

**Comment by kmsquire** [comment]
Test crashes should have been fixed by https://github.com/JuliaLang/julia/pull/23700.

@yuyichao @tkelman (or anyone), after such a fix is merged in mainline Julia, I assume rerunning the tests will pull in the latest build--is this true?  If so, how soon after a merge can the tests be rerun, in order to have the fix in place?

**Comment by yuyichao** [comment]
The nightly haven't been updated AFAICT as of a few minutes (to an hour) ago, which is longer than what I usually expect it to take. I've verified locally that the tests doesn't crash anymore though there are still test failures.

Those failures looks unrelated (`nextind` method error) and tests passes on released versions so I'll just merge this now.

**Comment by yuyichao** [comment]
And I might come back to check this later after finish dealing with other packages.

**Comment by kmsquire** [comment]
Thanks Yichao

**Pull request merged**
