### PR TITLE
Make "unrolled link list" clear, and link to Wikipedia [ci skip]

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
At least since/if not usable as such a list, a first step to complete https://github.com/JuliaCollections/DataStructures.jl/issues/339.

**Comment by PallHaraldsson** [comment]
Seems like I fixed from .md to .rst syntax (I learned something, not why both exist, or why here changed to this format, from MD, in the past..). Adding [ci skip] did probably nothing.. but anyway seems ok to just merge.

**Comment by oxinabox** [comment]
Thanks.
I think it is good to have these summeries in the readme.
It would be nice to have them in the full docs too.

I will merge once travis etc completes.
The `[ci skip]` needs  to be in the commit message, not the PR title.
(unfortunately)

**Comment by PallHaraldsson** [comment]
"I will merge once travis etc completes."

You mean you can't? I can't merge either way, I thought just a permission problem.

I'm not sure why CI is so slow, at least here where no actual code change.. but I'm in no hurry.

**Comment by kmsquire** [comment]
As noted in https://github.com/JuliaCollections/DataStructures.jl/issues/339#issuecomment-343750565, the underlying `DequeBlock` implementation is very similar to an unrolled linked-list, but access to/insertion to/deletion from arbitrary positions isn't implemented.

**Pull request merged**
