### PR TITLE
Conditional import of Base.isfull

### PR DESCRIPTION
**Pull request by KronosTheLate**
As suggested in [this](https://github.com/JuliaCollections/DataStructures.jl/issues/894#issuecomment-1925922689) comment in #894

### CODE REVIEW

**Comment by oxinabox** [comment]
Will merge once  https://github.com/JuliaLang/julia/pull/53159 is merged

**Comment by CameronBieganek** [comment]
This might qualify as punning. The docstring for `Base.isfull` is very specific to Channels---it does not provide a generic definition of `isfull` that could also apply to `DataStructures.CircularBuffer`.

**Comment by vtjnash** [comment]
Do you want to suggest a change on the Base PR? I think this function is very much the same concept as a general queue/stack implementation concept

**Comment by CameronBieganek** [comment]
I wouldn't recommend overloading `Base.isfull`. There is no indication that code written for `Base.isfull(c::Channel)` would have any applicability to `DataStructures.CircularBuffer`. They should remain separate functions.

The introduction of `Base.isfull` does not break `DataStructures` per se, it just introduces ambiguity errors in downstream code like this:

```julia
using DataStructures
x = # ...
isfull(x)
```

That's unfortunate, but the real issue is with the "import all" pattern. For code that needs to survive minor updates to dependencies, you need to write it like this instead:

```julia
using DataStructures: isfull
x = # ...
isfull(x)
```

**Comment by KronosTheLate** [comment]
> Will merge once [JuliaLang/julia#53159](https://github.com/JuliaLang/julia/pull/53159) is merged

That PR got merged yesterday.

**Comment by oxinabox** [comment]
merged and backported

**Pull request merged**
