### PR TITLE
Fix depwarns and errors on 0.7

### PR DESCRIPTION
**Pull request by yuyichao**
Turns out to be pretty straight forward...

This pass all the test on master without any unexpected depwarns. Passing on CI probably need a nightly update.....

### CODE REVIEW

**Comment by quinnj** [comment]
Bump; would be great to have this merged since it affects so many downstream packages.

**Comment by yuyichao** [comment]
I'm pretty sure most downstream packages just need a tag here. For this PR I only want a new julia nightly so I can actually check CI.

**Comment by yuyichao** [comment]
Linux nightly is somehow still stuck at almost right before the fix on master.... At least macOS and windows both pass now so merge...

**Comment by kevincheng97** [comment]
I still receive the following error trying to compile on 0.7:
"ERROR: LoadError: LoadError: LoadError: type QuoteNode has no field args
Stacktrace:
 [1] @delegate(::LineNumberNode, ::Module, ::Any, ::Any) at /Users/kevin/.julia/v0.7/DataFrames/src/statsmodels/statsmodel.jl:20
 [2] include_relative(::Module, ::String) at ./loading.jl:526
 [3] include at ./sysimg.jl:14 [inlined]
 [4] include(::String) at /Users/kevin/.julia/v0.7/DataFrames/src/DataFrames.jl:3
 [5] macro expansion at /Users/kevin/.julia/v0.7/DataFrames/src/DataFrames.jl:128 [inlined]
 [6] anonymous at ./<missing>:?
 [7] include_relative(::Module, ::String) at ./loading.jl:526
 [8] include(::Module, ::String) at ./sysimg.jl:14
 [9] anonymous at ./<missing>:2
in expression starting at /Users/kevin/.julia/v0.7/DataFrames/src/statsmodels/statsmodel.jl:62
in expression starting at /Users/kevin/.julia/v0.7/DataFrames/src/statsmodels/statsmodel.jl:62
in expression starting at /Users/kevin/.julia/v0.7/DataFrames/src/DataFrames.jl:97"

**Comment by mauro3** [comment]
@kevincheng97: please quote your code in backticks, for whole code blocks use ```` ``` ````. This is especially true for code containing macros, as you just pinged https://github.com/delegate who probably cares little about this issue.

**Comment by yuyichao** [comment]
This is `DataStructures`, not `DataFrames`.

**Comment by kevincheng97** [comment]
Oops sorry

**Pull request merged**
