### PR TITLE
Change enqueue! dequeue! to push! popfirst!

### PR DESCRIPTION
**Pull request by HenriDeh**
Attempt number two. I think I covered everything.

### CODE REVIEW

**Review by oxinabox — DISMISSED** [review]

**Comment by oxinabox** [comment]
LGTM, will merge once CI finished running

**Comment by oxinabox** [comment]
Looks like CI is failing
`invalid redefinition of constant enqueue!`
I guess because we still have `enqueue!` used elsewhere (for `dequeque`?)

So can't use `@deprecate_binding` will need to use `@deprecate enqueue(q::Queue, x) push!(q, x)`

**Comment by HenriDeh** [comment]
Should be fixed

**Comment by HenriDeh** [comment]
And now it should. Sorry, I'm working directly in Github so I can't spot mistakes before you run CI for me. I always leave stupid mistakes like this but I eventually manage to remove all of them.

**Comment by HenriDeh** [comment]
Since we're here: PriorityQueue is the last DS using the dequeue! enqueue! API. I can take care of it (in another PR) if you want. That way all the queues will use the same API (unless I missed another). 

There's still the Stack discussion #677 that initially spurred my original PR that should be resolved at some point (before 1.0 I guess).

**Comment by HenriDeh** [comment]
Yesss all checks passed. Finally ready to merge.

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
thanks!
and now Github won't need me to approve each CI for your future PRs

**Pull request merged**
