### PR TITLE
Implement sizehint! for heaps

### LINKED ISSUE #518: `sizehint!` is not implemented for heaps
The heap interface specification says that `sizehint!` methods should be implemented for heaps but they aren't. I can add these at the hackathon tomorrow

https://github.com/JuliaCollections/DataStructures.jl/blob/8ec394cba8561a42e1241dfde99f77ee4b7159af/src/heaps.jl#L25

### PR DESCRIPTION
**Pull request by harryscholes**
Fixes #518. Do we need to test these methods?

### CODE REVIEW

**Comment by kmsquire** [comment]
>Do we need to test these methods?

Preferably, yes.

**Comment by kmsquire** [comment]
And thank you for the contribution!

**Comment by harryscholes** [comment]
The tests pass, but I can't quite work the following out. I'm getting `MethodError`s for `sizehint!(heap, s)` when I have this branch dev'd on my local machine. Any idea what might be causing this? `sizehint!` is imported from `Base` and is exported by `DataStructures`.

```julia
julia> using DataStructures

julia> h = BinaryMaxHeap([1,2,3])
BinaryHeap{Int64,DataStructures.GreaterThan}(DataStructures.GreaterThan(), [3, 1, 2])

julia> sizehint!(h, 100)
ERROR: MethodError: no method matching sizehint!(::BinaryHeap{Int64,DataStructures.GreaterThan}, ::Int64)
Closest candidates are:
  sizehint!(::BitArray{1}, ::Integer) at bitarray.jl:768
  sizehint!(::BitSet, ::Integer) at bitset.jl:56
  sizehint!(::DataStructures.IntSet, ::Integer) at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/int_set.jl:25
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> methods(sizehint!)
# 18 methods for generic function "sizehint!":
[1] sizehint!(B::BitArray{1}, sz::Integer) in Base at bitarray.jl:768
[2] sizehint!(s::BitSet, n::Integer) in Base at bitset.jl:56
[3] sizehint!(s::DataStructures.IntSet, n::Integer) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/int_set.jl:25
[4] sizehint!(a::Array{T,1} where T, sz::Integer) in Base at array.jl:1022
[5] sizehint!(d::IdDict, newsz) in Base at abstractdict.jl:571
[6] sizehint!(s::Base.IdSet, newsz) in Base at abstractdict.jl:693
[7] sizehint!(d::Dict{T,V} where V, newsz) where T in Base at dict.jl:233
[8] sizehint!(s::Set, newsz) in Base at set.jl:64
[9] sizehint!(s::OrderedSet, sz::Integer) in OrderedCollections at /Users/harry/.julia/packages/OrderedCollections/E21Rb/src/ordered_set.jl:21
[10] sizehint!(s::AbstractSet, n) in Base at abstractset.jl:4
[11] sizehint!(d::OrderedDict, newsz) in OrderedCollections at /Users/harry/.julia/packages/OrderedCollections/E21Rb/src/ordered_dict.jl:200
[12] sizehint!(dd::LittleDict{K,V,Array{K,1},Array{V,1}} where V where K, sz) in OrderedCollections at /Users/harry/.julia/packages/OrderedCollections/E21Rb/src/little_dict.jl:175
[13] sizehint!(a::DataStructures.DefaultDictBase, args...) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/delegate.jl:37
[14] sizehint!(a::DefaultDict, args...) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/delegate.jl:37
[15] sizehint!(a::DefaultOrderedDict, args...) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/delegate.jl:37
[16] sizehint!(d::MultiDict, sz::Integer) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/multi_dict.jl:48
[17] sizehint!(d::RobinDict, newsz) in DataStructures at /Users/harry/.julia/packages/DataStructures/5F6tJ/src/robin_dict.jl:231
[18] sizehint!(X::DataValues.DataValueArray{T,1} where T, newsz::Integer) in DataValues at /Users/harry/.julia/packages/DataValues/XQWvG/src/array/datavaluevector.jl:220

```

**Comment by harryscholes** [comment]
Ahh. I'm not sure exactly what the cause is, but it's something to do with using a PackageCompiler.jl system image. When I reverted to the default system image my new `sizehint!` methods work as expected

**Comment by oxinabox** [comment]
thanks

**Pull request merged**
