### PR TITLE
Fix 0.6 typealias depwarn

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by andreasnoack** [comment]
It would be great with a new release of the package.

**Comment by kmsquire** [comment]
I've made some changes to `SortedDict` and company on master that would require a minor version number bump, but those changes aren't really complete yet.

So in order to tag a release, I'm going to create a `v0.5-release` branch, based off of the `v0.5.2` tag, and attempt to cherry-pick the various fixes applied since then, ignoring the `SortedDict` and `SortedSet` updates.

Assuming that works, I'll tag a new release off of that branch.

**Comment by kmsquire** [comment]
`v0.5.3` can be tagged using branch [`v0.5-release`](https://github.com/JuliaCollections/DataStructures.jl/tree/v0.5-release) once tests pass [here](https://travis-ci.org/JuliaCollections/DataStructures.jl/builds/204084328).

**Comment by kmsquire** [comment]
Linux tests pass, so I'm going to tag and head to bed.

**Pull request merged**
