### PR TITLE
Deprecate `deque` constructor

### PR DESCRIPTION
**Pull request by harryscholes**
From #606

### CODE REVIEW

**Comment by harryscholes** [comment]
Will do. There are a few other deprecations scattered around the codebase. Do you also want these moved into `deprecations.jl`?

**Comment by oxinabox** [comment]
> Will do. There are a few other deprecations scattered around the codebase. Do you also want these moved into deprecations.jl?

In general yes, not too rushed about fixing old failures, just about avoiding creating new ones.

**Comment by oxinabox** [comment]
I think this is not quite right since it causes an error. is there a missing `where` ?

**Comment by harryscholes** [comment]
Oops! Fixed now :)

**Comment by oxinabox** [comment]
thanks!

**Comment by giordano** [comment]
In v0.17.14 I'm seeing this warning
```
WARNING: Method definition deque(Type{T}) where {T} in module DataStructures at /home/runner/.julia/packages/DataStructures/w35Mo/src/deque.jl:89 overwritten at deprecated.jl:65.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by harryscholes** [comment]
Hmm why is this happening?

**Comment by harryscholes** [comment]
I think this is happening because `@deprecate` exports the deprecated function, but `deque` is still exported in `DataStructures.jl`.

**Comment by harryscholes** [comment]
Actually, no it's not because of that. Discussion continued in #615

**Pull request merged**
